Class {
	#name : #IllegalResumeAttempt,
	#superclass : #Exception,
	#category : #'Kernel-Exceptions'
}

{ #category : #all }
IllegalResumeAttempt >> defaultAction [
	"No one has handled this error, but now give them a chance to decide how to debug it.  If none handle this either then open debugger (see UnhandedError-defaultAction)"

	UnhandledError signalForException: self
]

{ #category : #all }
IllegalResumeAttempt >> isResumable [
	
	^ false
]
